### PR TITLE
fix: don't transform chain()

### LINKED ISSUE #444: missing information regarding `.chain()` optimizations
how does this plugin should be used with `.chain` and chained methods? I would expect some text regarding this and examples..

Thank you 😊

### PR DESCRIPTION
**Pull request by kyle-johnson**
Closes #444 

It's _possible_ this still works with lodash-es -- this needs testing before release (don't want to break that if it works).

Includes a small refactor to shift error handling up and make the happy-path top-level.

### CODE REVIEW

File: packages/transform/src/index.ts [hunk 1]
```diff
@@ -33,7 +34,7 @@ export function transform({
   code,
   id,
   parse,
-  warn,
+  warn = console.error,
```
Comment (kyle-johnson) [inline packages/transform/src/index.ts:37]: This shouldn't be a breaking change, but does remove a check down below
